annotations:
  category: CMS
apiVersion: v2
appVersion: 5.6.1
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://buckbuckgo.s3.ir-thr-at1.arvanstorage.com
    version: 9.x.x
  - name: common
    repository: https://buckbuckgo.s3.ir-thr-at1.arvanstorage.com
    tags:
      - bitnami-common
    version: 1.x.x
description: Web publishing platform for building blogs and websites.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/wordpress
icon: https://bitnami.com/assets/stacks/wordpress/img/wordpress-stack-220x234.png
keywords:
  - application
  - blog
  - cms
  - http
  - php
  - web
  - wordpress
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: wordpress
sources:
  - https://github.com/bitnami/bitnami-docker-wordpress
  - http://www.wordpress.com/
version: 10.6.3
